# Generated by Django 5.2.6 on 2025-09-11 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIItinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField()),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('budget', models.CharField(choices=[('budget', 'Budget'), ('mid-range', 'Mid-range'), ('luxury', 'Luxury')], default='mid-range', max_length=20)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('travel_style', models.CharField(choices=[('cultural', 'Cultural'), ('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('family', 'Family'), ('romantic', 'Romantic'), ('solo', 'Solo'), ('business', 'Business')], default='cultural', max_length=20)),
                ('interests', models.TextField(help_text='Comma-separated interests')),
                ('accommodation_preference', models.CharField(blank=True, max_length=100)),
                ('transportation_preference', models.CharField(blank=True, max_length=100)),
                ('itinerary_content', models.JSONField(help_text='AI-generated itinerary in JSON format')),
                ('budget_breakdown', models.JSONField(help_text='AI-generated budget breakdown')),
                ('recommendations', models.JSONField(default=list, help_text='Additional recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model_used', models.CharField(default='gemini-pro', max_length=50)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken to generate in seconds', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Itinerary',
                'verbose_name_plural': 'AI Itineraries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('itinerary', 'Itinerary Generation'), ('budget', 'Budget Estimation'), ('recommendations', 'Recommendations')], max_length=50)),
                ('prompt_sent', models.TextField()),
                ('response_received', models.TextField()),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='ai_travel.aiitinerary')),
            ],
            options={
                'verbose_name': 'AI Generation Log',
                'verbose_name_plural': 'AI Generation Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accommodation_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accommodation_recommendations', models.JSONField(default=list)),
                ('transportation_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation_breakdown', models.JSONField(default=dict)),
                ('food_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dining_recommendations', models.JSONField(default=list)),
                ('activities_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activities_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activities_breakdown', models.JSONField(default=list)),
                ('shopping_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shopping_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('miscellaneous', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emergency_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_alternatives', models.JSONField(default=list, help_text='Budget-friendly alternatives')),
                ('luxury_alternatives', models.JSONField(default=list, help_text='Luxury alternatives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_budget', to='ai_travel.aiitinerary')),
            ],
            options={
                'verbose_name': 'Budget Estimate',
                'verbose_name_plural': 'Budget Estimates',
            },
        ),
    ]
