# Generated by Django 5.2.5 on 2025-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiitinerary',
            name='ai_model_used',
            field=models.CharField(default='simple-ai', max_length=50),
        ),
    ]
