# Generated by Django 5.2.5 on 2025-09-04 18:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('travelers', models.IntegerField(default=1)),
                ('interests', models.JSONField(default=list)),
                ('budget_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itinerary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adults', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('children', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('infants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('budget_per_person', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('hostel', 'Hostel'), ('apartment', 'Apartment'), ('guesthouse', 'Guesthouse'), ('camping', 'Camping'), ('other', 'Other')], default='hotel', max_length=20)),
                ('transportation_mode', models.CharField(choices=[('flight', 'Flight'), ('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('ship', 'Ship'), ('mixed', 'Mixed'), ('other', 'Other')], default='flight', max_length=20)),
                ('interests', models.JSONField(default=list)),
                ('special_requirements', models.TextField(blank=True)),
                ('itinerary', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=dict)),
                ('booking_links', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('booked', 'Booked'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Plan',
                'verbose_name_plural': 'Trip Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('taken_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.tripplan')),
            ],
            options={
                'verbose_name': 'Trip Photo',
                'verbose_name_plural': 'Trip Photos',
                'ordering': ['-taken_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accommodation', 'Accommodation'), ('transportation', 'Transportation'), ('food', 'Food & Dining'), ('activities', 'Activities & Tours'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('miscellaneous', 'Miscellaneous')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('expense_date', models.DateField()),
                ('receipt_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.tripplan')),
            ],
            options={
                'verbose_name': 'Trip Expense',
                'verbose_name_plural': 'Trip Expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
