# Generated by Django 5.2.5 on 2025-09-04 18:06

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('accommodation_type', models.CharField(blank=True, max_length=100)),
                ('transportation_mode', models.CharField(blank=True, max_length=100)),
                ('interests', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('itinerary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreeTripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('continent', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('trip_count', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Free Trip Location',
                'verbose_name_plural': 'Free Trip Locations',
                'ordering': ['-popularity_score', 'name'],
                'indexes': [models.Index(fields=['country'], name='free_trips__country_5c9d45_idx'), models.Index(fields=['popularity_score'], name='free_trips__popular_b532e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FreeTripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('destination', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('adults', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('children', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('accommodation_type', models.CharField(choices=[('budget', 'Budget (Hostels, Budget Hotels)'), ('mid-range', 'Mid-Range (3-star Hotels)'), ('luxury', 'Luxury (4-5 star Hotels)'), ('apartment', 'Apartment/Airbnb'), ('mixed', 'Mixed Options')], default='mid-range', max_length=20)),
                ('transportation_mode', models.CharField(choices=[('budget', 'Budget (Bus, Budget Airlines)'), ('standard', 'Standard (Regular Airlines, Train)'), ('premium', 'Premium (Business Class, First Class)'), ('mixed', 'Mixed Options')], default='standard', max_length=20)),
                ('trip_type', models.CharField(choices=[('adventure', 'Adventure & Outdoor'), ('cultural', 'Cultural & Historical'), ('relaxation', 'Beach & Relaxation'), ('city', 'City Break'), ('nature', 'Nature & Wildlife'), ('family', 'Family Friendly'), ('romantic', 'Romantic Getaway'), ('business', 'Business Travel'), ('mixed', 'Mixed Interests')], default='mixed', max_length=20)),
                ('interests', models.JSONField(default=list)),
                ('special_requirements', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('itinerary', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=dict)),
                ('estimated_costs', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'verbose_name': 'Free Trip Plan',
                'verbose_name_plural': 'Free Trip Plans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='free_trips__session_0e99d8_idx'), models.Index(fields=['destination'], name='free_trips__destina_ee96c4_idx'), models.Index(fields=['created_at'], name='free_trips__created_c3c8e4_idx')],
            },
        ),
    ]
